
spring:
    jpa:
      database-platform: MYSQL
    datasource:
        name: test
        url: jdbc:mysql://8.9.6.166:3306/datamanagement?allowMultiQueries=true
#        url: jdbc:mysql://39.104.108.113:3306/data?allowMultiQueries=true
        username: root


#        password: ShuMei123_
        password: 184593
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

#    redis:
#      database: 0
#      host: localhost
#      port: 6379
#      password:

    output:
      ansi:
        enabled: detect
    thymeleaf:
      cache: false
#    jackson:
#      serialization: true
#      time-zone: GMT+8
#      date-format: yyyy-MM-dd HH:mm


server:
  port: 8080
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.ncu.model
logging:
  pattern:
    console: "%d - %msg%n"
#  path: C:\logs
  path: /usr/log
  level:
    com.ncu.dao: DEBUG
#  file: C:\logs

#debug: false

#pagehelper分页插件配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#    dialect: com.github.pagehelper.dialect.helper.MySqlDialect


attachmentUrl: /home/static/
#attachmentUrl: C:\Users\12909\Desktop\3-19\

